# Generated by Django 4.1.1 on 2022-10-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='importance',
            field=models.CharField(default='не срочно', max_length=12, verbose_name='Очень срочно/срочно/не срочно '),
            preserve_default=False,
        ),
    ]
